# Generated by Django 5.0 on 2024-02-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=100)),
                ('Appointment_time', models.CharField(max_length=100)),
                ('Reason_for_the_appointment', models.CharField(max_length=100)),
                ('otp_number', models.CharField(max_length=20)),
            ],
        ),
    ]
