# Generated by Django 5.0 on 2024-02-15 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_table',
            name='otp_number',
        ),
    ]
