# Generated by Django 5.0 on 2024-02-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0003_rename_appointment_time_register_table_appointment_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_table',
            name='otp_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
